Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
127.0.0.1 - - [18/Jun/2025 08:55:50] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:50] "GET /style.css HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:50] "GET /logo.png HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:50] "GET /Rapport-schon-matteo.pdf HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:50] "GET /Rapport-lucas-lemaire.pdf HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:50] "GET /video1.mp4 HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:52] "GET /3-po/po.html HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:52] "GET /3-po/prehenseur.jpg HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:52] "GET /3-po/bras.jpg HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:54] "GET /7-doctech/doctech.html HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:54] "GET /2-securite/securite.html HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:56] "GET /index.html HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:56] "GET /Rapport-schon-matteo.pdf HTTP/1.1" 200 -
127.0.0.1 - - [18/Jun/2025 08:55:56] "GET /video1.mp4 HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 43070)
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/socketserver.py", line 691, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/local/lib/python3.11/http/server.py", line 1310, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/usr/local/lib/python3.11/http/server.py", line 671, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.11/socketserver.py", line 755, in __init__
    self.handle()
  File "/usr/local/lib/python3.11/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/usr/local/lib/python3.11/http/server.py", line 424, in handle_one_request
    method()
  File "/usr/local/lib/python3.11/http/server.py", line 678, in do_GET
    self.copyfile(f, self.wfile)
  File "/usr/local/lib/python3.11/http/server.py", line 877, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/usr/local/lib/python3.11/shutil.py", line 200, in copyfileobj
    fdst_write(buf)
  File "/usr/local/lib/python3.11/socketserver.py", line 834, in write
    self._sock.sendall(b)
ConnectionResetError: [Errno 104] Connection reset by peer
----------------------------------------
